### ISSUE TITLE
DogStatsd client stops sending metrics after Datadog agent restarts

### ISSUE THREAD

**Issue by fhervieux** [DataDog/dogstatsd-csharp-client#150] opened 2020-11-24 10:34 UTC
DogStatsd client version: 5.0.2
Datadog agent version: 7.21.1
Datadog helm chart version: 2.4.14

We are encountering an issue with a Kubernetes setup. Datadog agent is deployed as a Helm chart, containers using the Dogstatsd client are based on the mcr.microsoft.com/dotnet/core/aspnet:3.1 image. The containers are sending gauge metrics using the Dogstatsd client. Every time the agent restarts, metrics stop being sent. A restart of the client container is needed. No error or exception seem to indicate any problem.

This seems to be related to the PR #125 but we are using the version 5.0.2 so it could also be unrelated.

If you need more information I can get it. Thanks!

**Comment by ogaca-dd** [comment] 2021-03-24 13:50
Hi @fhervieux ,

Sorry for my late answer.
This issue was reported to our support team and the solution is to use Unix Domain Socket instead of UDP.  See [Unix domain socket support](https://github.com/DataDog/dogstatsd-csharp-client#unix-domain-socket-support) to enable Unix domain socket.

**Comment by fhervieux** [comment] 2021-04-15 20:52
Using Unix Domain Socket seems to fix the problem. It does not occur anymore. Thank you!

**Comment by ogaca-dd** [comment] 2022-09-23 12:04
Closed as the issue is fixed.

**Closed by ogaca-dd** 2022-09-23 12:04 UTC
Labels: question
